### ISSUE TITLE
Reduce tracking on mitmproxy.org

### ISSUE THREAD

**Issue by mhils** [mitmproxy/www#24]
mitmproxy itself is completely free of any tracking, but we have some room of improvement on the website:

- [x] Replace all resources loaded from CDNs with local copies.
- [x] Check if we can remove the referrer for the GitHub stars API call.
- [x] Consider ditching Google Analytics. We have some very basic stats from AWS CloudFront, which should be good enough.
- [ ] Figure out if we can do something about the embedded tweet list. This is arguably the most difficult one, but maybe also the worst offender.

Most of these tasks should be doable for anyone, help is greatly appreciated!
